name: AutoRun

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r calculator/reqs.txt

    - name: Run unit tests
      run: |
        python calculator/unit_test.py

    - name: Build installer
      run: |
        cd calculator
        python setup.py sdist
        cd ..

    - name: Install application
      run: |
        pip install calculator/dist/CalculatorApp-1.0.tar.gz

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: calculator/dist/
